package oo12;

import static org.junit.Assert.*;

import org.junit.Before;
import org.junit.Test;

public class NewElevatorTest {

	@Before
	public void setUp() throws Exception {
			for(int i = 0;i<10000;i++){
				Queue.getQueue()[i][0]=null;
				Queue.getQueue()[i][1]=null;
				Queue.getQueue()[i][2]=null;
				Queue.getQueue()[i][3]=null;
			}
			for(int i=0;i<1000;i++){
				NewElevator.Waitinglist[i][1]=null;
				NewElevator.Waitinglist[i][1]=null;
				NewElevator.Waitinglist[i][1]=null;
				NewElevator.Waitinglist[i][1]=null;
			}
	}
	NewElevator aa=new NewElevator();
	@Test
	public void testRun() throws Exception {
		
		Queue.insetfr(true,"FR","1","UP","0",Queue.getQueue());
		Queue.inseter(true,"ER","1","0",Queue.getQueue());
		Queue.insetfr(true,"FR","8","DOWN","2",Queue.getQueue());
		Queue.inseter(true,"ER","8","2",Queue.getQueue());
		Queue.inseter(true,"ER","7","5",Queue.getQueue());
		Queue.insetfr(true,"FR","1","UP","6",Queue.getQueue());
		Queue.inseter(true,"ER","1","6",Queue.getQueue());
		Queue.inseter(true,"ER","5","6",Queue.getQueue());
		Queue.insetfr(true,"FR","4","DOWN","7",Queue.getQueue());
		Queue.inseter(true,"ER","4","7",Queue.getQueue());
		Queue.inseter(true,"ER","2","10",Queue.getQueue());
		Queue.inseter(true,"ER","7","11",Queue.getQueue());
		Queue.insetfr(true,"FR","6","DOWN","11",Queue.getQueue());
		Queue.inseter(true,"ER","6","11",Queue.getQueue());
		Queue.insetfr(true,"FR","3","UP","14",Queue.getQueue());
		Queue.inseter(true,"ER","3","14",Queue.getQueue());
		Queue.inseter(true,"ER","1","15",Queue.getQueue());
		Queue.insetfr(true,"FR","6","UP","18",Queue.getQueue());
		Queue.inseter(true,"ER","6","18",Queue.getQueue());
		Queue.insetfr(true,"FR","4","UP","20",Queue.getQueue());
		Queue.inseter(true,"ER","4","20",Queue.getQueue());
		Queue.inseter(true,"ER","5","23",Queue.getQueue());
		Queue.insetfr(true,"FR","10","UP","24",Queue.getQueue());
		Queue.inseter(true,"ER","10","24",Queue.getQueue());
		Queue.inseter(true,"ER","6","26",Queue.getQueue());
		Queue.insetfr(true,"FR","9","DOWN","29",Queue.getQueue());
		Queue.inseter(true,"ER","9","29",Queue.getQueue());
		Queue.insetfr(true,"FR","10","DOWN","32",Queue.getQueue());
		Queue.inseter(true,"ER","10","32",Queue.getQueue());
		Queue.inseter(true,"ER","6","36",Queue.getQueue());
		Queue.insetfr(true,"FR","10","UP","37",Queue.getQueue());
		Queue.inseter(true,"ER","10","37",Queue.getQueue());
		Queue.inseter(true,"ER","10","37",Queue.getQueue());
		Queue.insetfr(true,"FR","2","DOWN","37",Queue.getQueue());
		Queue.inseter(true,"ER","2","37",Queue.getQueue());
		Queue.insetfr(true,"FR","5","UP","39",Queue.getQueue());
		Queue.inseter(true,"ER","5","39",Queue.getQueue());
		Queue.insetfr(true,"FR","4","DOWN","40",Queue.getQueue());
		Queue.inseter(true,"ER","4","40",Queue.getQueue());
		Queue.inseter(true,"ER","7","43",Queue.getQueue());
		Queue.insetfr(true,"FR","2","DOWN","44",Queue.getQueue());
		Queue.inseter(true,"ER","2","44",Queue.getQueue());
		Queue.inseter(true,"ER","1","47",Queue.getQueue());
		Queue.insetfr(true,"FR","2","DOWN","47",Queue.getQueue());
		Queue.inseter(true,"ER","2","47",Queue.getQueue());
		Queue.inseter(true,"ER","4","48",Queue.getQueue());
		Queue.insetfr(true,"FR","5","UP","49",Queue.getQueue());
		Queue.inseter(true,"ER","5","49",Queue.getQueue());
		Queue.inseter(true,"ER","3","52",Queue.getQueue());
		Queue.insetfr(true,"FR","10","DOWN","53",Queue.getQueue());
		Queue.inseter(true,"ER","10","53",Queue.getQueue());
		Queue.insetfr(true,"FR","7","UP","56",Queue.getQueue());
		Queue.inseter(true,"ER","7","56",Queue.getQueue());
		Queue.insetfr(true,"FR","4","UP","57",Queue.getQueue());
		Queue.inseter(true,"ER","4","57",Queue.getQueue());
		Queue.inseter(true,"ER","7","58",Queue.getQueue());
		Queue.insetfr(true,"FR","10","DOWN","61",Queue.getQueue());
		Queue.inseter(true,"ER","10","61",Queue.getQueue());
		Queue.insetfr(true,"FR","10","DOWN","63",Queue.getQueue());
		Queue.inseter(true,"ER","10","63",Queue.getQueue());
		Queue.inseter(true,"ER","4","65",Queue.getQueue());
		Queue.insetfr(true,"FR","9","DOWN","67",Queue.getQueue());
		Queue.inseter(true,"ER","9","67",Queue.getQueue());
		Queue.inseter(true,"ER","3","69",Queue.getQueue());
		Queue.insetfr(true,"FR","7","UP","73",Queue.getQueue());
		Queue.inseter(true,"ER","7","73",Queue.getQueue());
		Queue.inseter(true,"ER","8","74",Queue.getQueue());
		Queue.inseter(true,"ER","4","74",Queue.getQueue());
		Queue.inseter(true,"ER","1","78",Queue.getQueue());
		Queue.insetfr(true,"FR","5","UP","84",Queue.getQueue());
		Queue.inseter(true,"ER","5","84",Queue.getQueue());
		Queue.inseter(true,"ER","9","85",Queue.getQueue());
		Queue.insetfr(true,"FR","8","DOWN","85",Queue.getQueue());
		Queue.inseter(true,"ER","8","85",Queue.getQueue());
		Queue.inseter(true,"ER","1","87",Queue.getQueue());
		Queue.inseter(true,"ER","7","87",Queue.getQueue());
		Queue.inseter(true,"ER","10","88",Queue.getQueue());
		Queue.inseter(true,"ER","9","88",Queue.getQueue());
		Queue.insetfr(true,"FR","6","UP","88",Queue.getQueue());
		Queue.inseter(true,"ER","6","88",Queue.getQueue());
		Queue.insetfr(true,"FR","5","DOWN","88",Queue.getQueue());
		Queue.inseter(true,"ER","5","88",Queue.getQueue());
		Queue.insetfr(true,"FR","7","DOWN","91",Queue.getQueue());
		Queue.inseter(true,"ER","7","91",Queue.getQueue());
		Queue.inseter(true,"ER","10","93",Queue.getQueue());
		Queue.insetfr(true,"FR","1","UP","98",Queue.getQueue());
		Queue.inseter(true,"ER","1","98",Queue.getQueue());
		Queue.insetfr(true,"FR","1","UP","101",Queue.getQueue());
		Queue.inseter(true,"ER","1","101",Queue.getQueue());
		Queue.insetfr(true,"FR","8","DOWN","102",Queue.getQueue());
		Queue.inseter(true,"ER","8","102",Queue.getQueue());
		Queue.inseter(true,"ER","3","104",Queue.getQueue());
		Queue.inseter(true,"ER","2","106",Queue.getQueue());
		Queue.inseter(true,"ER","7","109",Queue.getQueue());
		Queue.insetfr(true,"FR","9","UP","111",Queue.getQueue());
		Queue.inseter(true,"ER","9","111",Queue.getQueue());
		Queue.insetfr(true,"FR","3","UP","111",Queue.getQueue());
		Queue.inseter(true,"ER","3","111",Queue.getQueue());
		Queue.insetfr(true,"FR","7","UP","112",Queue.getQueue());
		Queue.inseter(true,"ER","7","112",Queue.getQueue());
		Queue.insetfr(true,"FR","8","UP","114",Queue.getQueue());
		Queue.inseter(true,"ER","8","114",Queue.getQueue());
		Queue.inseter(true,"ER","3","117",Queue.getQueue());
		Queue.inseter(true,"ER","2","120",Queue.getQueue());
		Queue.insetfr(true,"FR","3","UP","120",Queue.getQueue());
		Queue.inseter(true,"ER","3","120",Queue.getQueue());
		Queue.inseter(true,"ER","6","120",Queue.getQueue());
		Queue.inseter(true,"ER","4","121",Queue.getQueue());
		Queue.insetfr(true,"FR","6","UP","122",Queue.getQueue());
		Queue.inseter(true,"ER","6","122",Queue.getQueue());
		Queue.inseter(true,"ER","5","123",Queue.getQueue());
		Queue.insetfr(true,"FR","6","UP","123",Queue.getQueue());
		Queue.inseter(true,"ER","6","123",Queue.getQueue());
		Queue.inseter(true,"ER","1","125",Queue.getQueue());
		Queue.insetfr(true,"FR","7","UP","127",Queue.getQueue());
		Queue.inseter(true,"ER","7","127",Queue.getQueue());
		Queue.insetfr(true,"FR","5","DOWN","128",Queue.getQueue());
		Queue.inseter(true,"ER","5","128",Queue.getQueue());
		Queue.insetfr(true,"FR","8","UP","131",Queue.getQueue());
		Queue.inseter(true,"ER","8","131",Queue.getQueue());
		Queue.inseter(true,"ER","6","134",Queue.getQueue());
		Queue.insetfr(true,"FR","6","UP","137",Queue.getQueue());
		Queue.inseter(true,"ER","6","137",Queue.getQueue());
		Queue.insetfr(true,"FR","7","DOWN","137",Queue.getQueue());
		Queue.inseter(true,"ER","7","137",Queue.getQueue());
		Queue.inseter(true,"ER","6","137",Queue.getQueue());
		Queue.inseter(true,"ER","6","138",Queue.getQueue());
		Queue.inseter(true,"ER","8","143",Queue.getQueue());
		Queue.insetfr(true,"FR","4","DOWN","145",Queue.getQueue());
		Queue.inseter(true,"ER","4","145",Queue.getQueue());
		Queue.inseter(true,"ER","1","146",Queue.getQueue());
		Queue.inseter(true,"ER","3","146",Queue.getQueue());
		Queue.inseter(true,"ER","7","148",Queue.getQueue());
		Queue.inseter(true,"ER","9","148",Queue.getQueue());
		Queue.insetfr(true,"FR","3","DOWN","150",Queue.getQueue());
		Queue.inseter(true,"ER","3","150",Queue.getQueue());
		Queue.insetfr(true,"FR","6","UP","152",Queue.getQueue());
		Queue.inseter(true,"ER","6","152",Queue.getQueue());
		Queue.inseter(true,"ER","9","153",Queue.getQueue());
		Queue.inseter(true,"ER","1","156",Queue.getQueue());
		Queue.insetfr(true,"FR","4","DOWN","157",Queue.getQueue());
		Queue.inseter(true,"ER","4","157",Queue.getQueue());
		Queue.inseter(true,"ER","10","158",Queue.getQueue());
		Queue.insetfr(true,"FR","6","UP","165",Queue.getQueue());
		Queue.inseter(true,"ER","6","165",Queue.getQueue());
		Queue.insetfr(true,"FR","7","DOWN","168",Queue.getQueue());
		Queue.inseter(true,"ER","7","168",Queue.getQueue());
		Queue.inseter(true,"ER","7","170",Queue.getQueue());
		Queue.insetfr(true,"FR","4","DOWN","172",Queue.getQueue());
		Queue.inseter(true,"ER","4","172",Queue.getQueue());
		Queue.insetfr(true,"FR","1","UP","172",Queue.getQueue());
		Queue.inseter(true,"ER","1","172",Queue.getQueue());
		Queue.inseter(true,"ER","8","175",Queue.getQueue());
		Queue.inseter(true,"ER","7","177",Queue.getQueue());
		Queue.insetfr(true,"FR","2","DOWN","183",Queue.getQueue());
		Queue.inseter(true,"ER","2","183",Queue.getQueue());
		Queue.inseter(true,"ER","2","185",Queue.getQueue());
		Queue.insetfr(true,"FR","1","UP","186",Queue.getQueue());
		Queue.inseter(true,"ER","1","186",Queue.getQueue());
		Queue.inseter(true,"ER","2","188",Queue.getQueue());
		Queue.inseter(true,"ER","7","193",Queue.getQueue());
		Queue.inseter(true,"ER","10","194",Queue.getQueue());
		Queue.inseter(true,"ER","3","194",Queue.getQueue());
		Queue.inseter(true,"ER","4","194",Queue.getQueue());
		Queue.inseter(true,"ER","2","197",Queue.getQueue());
		Queue.insetfr(true,"FR","10","UP","198",Queue.getQueue());
		Queue.inseter(true,"ER","10","198",Queue.getQueue());
		Queue.inseter(true,"ER","7","199",Queue.getQueue());
		Queue.inseter(true,"ER","6","200",Queue.getQueue());
		Queue.insetfr(true,"FR","7","UP","203",Queue.getQueue());
		Queue.inseter(true,"ER","7","203",Queue.getQueue());
		Queue.insetfr(true,"FR","3","UP","205",Queue.getQueue());
		Queue.inseter(true,"ER","3","205",Queue.getQueue());
		Queue.inseter(true,"ER","1","205",Queue.getQueue());
		Queue.inseter(true,"ER","5","206",Queue.getQueue());
		Queue.inseter(true,"ER","9","208",Queue.getQueue());
		Queue.insetfr(true,"FR","6","UP","209",Queue.getQueue());
		Queue.inseter(true,"ER","6","209",Queue.getQueue());
		Queue.inseter(true,"ER","7","209",Queue.getQueue());
		Queue.insetfr(true,"FR","4","DOWN","212",Queue.getQueue());
		Queue.inseter(true,"ER","4","212",Queue.getQueue());
		Queue.insetfr(true,"FR","7","UP","215",Queue.getQueue());
		Queue.inseter(true,"ER","7","215",Queue.getQueue());
		Queue.insetfr(true,"FR","5","UP","215",Queue.getQueue());
		Queue.inseter(true,"ER","5","215",Queue.getQueue());
		Queue.insetfr(true,"FR","4","DOWN","216",Queue.getQueue());
		Queue.inseter(true,"ER","4","216",Queue.getQueue());
		Queue.inseter(true,"ER","5","217",Queue.getQueue());
		Queue.inseter(true,"ER","10","217",Queue.getQueue());
		Queue.inseter(true,"ER","10","219",Queue.getQueue());
		Queue.inseter(true,"ER","1","220",Queue.getQueue());
		Queue.inseter(true,"ER","7","222",Queue.getQueue());
		Queue.insetfr(true,"FR","3","UP","225",Queue.getQueue());
		Queue.inseter(true,"ER","3","225",Queue.getQueue());
		Queue.inseter(true,"ER","2","227",Queue.getQueue());
		Queue.inseter(true,"ER","1","227",Queue.getQueue());
		Queue.inseter(true,"ER","8","228",Queue.getQueue());
		Queue.inseter(true,"ER","8","231",Queue.getQueue());
		Queue.insetfr(true,"FR","5","UP","231",Queue.getQueue());
		Queue.inseter(true,"ER","5","231",Queue.getQueue());
		Queue.insetfr(true,"FR","4","UP","234",Queue.getQueue());
		Queue.inseter(true,"ER","4","234",Queue.getQueue());
		Queue.insetfr(true,"FR","10","DOWN","236",Queue.getQueue());
		Queue.inseter(true,"ER","10","236",Queue.getQueue());
		Queue.insetfr(true,"FR","3","DOWN","239",Queue.getQueue());
		Queue.inseter(true,"ER","3","239",Queue.getQueue());
		Queue.inseter(true,"ER","4","241",Queue.getQueue());
		Queue.inseter(true,"ER","8","242",Queue.getQueue());
		Queue.inseter(true,"ER","8","245",Queue.getQueue());
		Queue.insetfr(true,"FR","7","DOWN","247",Queue.getQueue());
		Queue.inseter(true,"ER","7","247",Queue.getQueue());
		Queue.inseter(true,"ER","5","250",Queue.getQueue());
		Queue.inseter(true,"ER","5","252",Queue.getQueue());
		Queue.insetfr(true,"FR","4","DOWN","252",Queue.getQueue());
		Queue.inseter(true,"ER","4","252",Queue.getQueue());
		Queue.insetfr(true,"FR","5","DOWN","255",Queue.getQueue());
		Queue.inseter(true,"ER","5","255",Queue.getQueue());
		Queue.inseter(true,"ER","7","255",Queue.getQueue());
		Queue.insetfr(true,"FR","10","DOWN","256",Queue.getQueue());
		Queue.inseter(true,"ER","10","256",Queue.getQueue());
		Queue.inseter(true,"ER","6","258",Queue.getQueue());
		Queue.inseter(true,"ER","4","261",Queue.getQueue());
		Queue.insetfr(true,"FR","4","UP","263",Queue.getQueue());
		Queue.inseter(true,"ER","4","263",Queue.getQueue());
		Queue.insetfr(true,"FR","8","DOWN","264",Queue.getQueue());
		Queue.inseter(true,"ER","8","264",Queue.getQueue());
		Queue.inseter(true,"ER","7","265",Queue.getQueue());
		Queue.inseter(true,"ER","8","266",Queue.getQueue());
		Queue.inseter(true,"ER","5","266",Queue.getQueue());
		Queue.insetfr(true,"FR","5","UP","266",Queue.getQueue());
		Queue.inseter(true,"ER","5","266",Queue.getQueue());
		Queue.inseter(true,"ER","7","267",Queue.getQueue());
		Queue.inseter(true,"ER","3","268",Queue.getQueue());
		Queue.insetfr(true,"FR","8","DOWN","269",Queue.getQueue());
		Queue.inseter(true,"ER","8","269",Queue.getQueue());
		Queue.inseter(true,"ER","10","269",Queue.getQueue());
		Queue.insetfr(true,"FR","3","UP","272",Queue.getQueue());
		Queue.inseter(true,"ER","3","272",Queue.getQueue());
		Queue.inseter(true,"ER","5","272",Queue.getQueue());
		Queue.inseter(true,"ER","2","272",Queue.getQueue());
		Queue.inseter(true,"ER","10","272",Queue.getQueue());
		Queue.inseter(true,"ER","6","274",Queue.getQueue());
		Queue.inseter(true,"ER","2","274",Queue.getQueue());
		Queue.inseter(true,"ER","6","276",Queue.getQueue());
		Queue.insetfr(true,"FR","8","DOWN","277",Queue.getQueue());
		Queue.inseter(true,"ER","8","277",Queue.getQueue());
		Queue.insetfr(true,"FR","8","UP","280",Queue.getQueue());
		Queue.inseter(true,"ER","8","280",Queue.getQueue());
		Queue.insetfr(true,"FR","5","DOWN","281",Queue.getQueue());
		Queue.inseter(true,"ER","5","281",Queue.getQueue());
		Queue.inseter(true,"ER","6","281",Queue.getQueue());
		Queue.insetfr(true,"FR","2","DOWN","283",Queue.getQueue());
		Queue.inseter(true,"ER","2","283",Queue.getQueue());
		Queue.inseter(true,"ER","6","285",Queue.getQueue());
		Queue.inseter(true,"ER","3","288",Queue.getQueue());
		Queue.inseter(true,"ER","10","289",Queue.getQueue());
		Queue.insetfr(true,"FR","8","UP","289",Queue.getQueue());
		Queue.inseter(true,"ER","8","289",Queue.getQueue());
		Queue.insetfr(true,"FR","4","UP","290",Queue.getQueue());
		Queue.inseter(true,"ER","4","290",Queue.getQueue());
		Queue.inseter(true,"ER","10","291",Queue.getQueue());
		Queue.insetfr(true,"FR","6","UP","292",Queue.getQueue());
		Queue.inseter(true,"ER","6","292",Queue.getQueue());
		Queue.insetfr(true,"FR","7","UP","295",Queue.getQueue());
		Queue.inseter(true,"ER","7","295",Queue.getQueue());
		Queue.inseter(true,"ER","6","296",Queue.getQueue());
		Queue.insetfr(true,"FR","4","DOWN","297",Queue.getQueue());
		Queue.inseter(true,"ER","4","297",Queue.getQueue());
		Queue.inseter(true,"ER","5","299",Queue.getQueue());
		Queue.insetfr(true,"FR","5","DOWN","301",Queue.getQueue());
		Queue.inseter(true,"ER","5","301",Queue.getQueue());
		Queue.insetfr(true,"FR","5","UP","303",Queue.getQueue());
		Queue.inseter(true,"ER","5","303",Queue.getQueue());
		Queue.insetfr(true,"FR","2","UP","303",Queue.getQueue());
		Queue.inseter(true,"ER","2","303",Queue.getQueue());
		Queue.inseter(true,"ER","2","303",Queue.getQueue());
		Queue.insetfr(true,"FR","7","DOWN","303",Queue.getQueue());
		Queue.inseter(true,"ER","7","303",Queue.getQueue());
		Queue.insetfr(true,"FR","6","UP","306",Queue.getQueue());
		Queue.inseter(true,"ER","6","306",Queue.getQueue());
		Queue.insetfr(true,"FR","7","UP","308",Queue.getQueue());
		Queue.inseter(true,"ER","7","308",Queue.getQueue());
		Queue.insetfr(true,"FR","2","DOWN","311",Queue.getQueue());
		Queue.inseter(true,"ER","2","311",Queue.getQueue());
		Queue.insetfr(true,"FR","6","DOWN","314",Queue.getQueue());
		Queue.inseter(true,"ER","6","314",Queue.getQueue());
		Queue.insetfr(true,"FR","4","DOWN","317",Queue.getQueue());
		Queue.inseter(true,"ER","4","317",Queue.getQueue());
		Queue.inseter(true,"ER","3","317",Queue.getQueue());
		Queue.inseter(true,"ER","6","317",Queue.getQueue());
		Queue.inseter(true,"ER","10","318",Queue.getQueue());
		Queue.inseter(true,"ER","8","320",Queue.getQueue());
		Queue.insetfr(true,"FR","9","DOWN","322",Queue.getQueue());
		Queue.inseter(true,"ER","9","322",Queue.getQueue());
		Queue.inseter(true,"ER","3","325",Queue.getQueue());
		Queue.inseter(true,"ER","7","325",Queue.getQueue());
		Queue.insetfr(true,"FR","4","DOWN","326",Queue.getQueue());
		Queue.inseter(true,"ER","4","326",Queue.getQueue());
		Queue.inseter(true,"ER","4","329",Queue.getQueue());
		Queue.insetfr(true,"FR","8","UP","330",Queue.getQueue());
		Queue.inseter(true,"ER","8","330",Queue.getQueue());
		Queue.inseter(true,"ER","2","333",Queue.getQueue());
		Queue.insetfr(true,"FR","3","UP","336",Queue.getQueue());
		Queue.inseter(true,"ER","3","336",Queue.getQueue());
		Queue.inseter(true,"ER","5","336",Queue.getQueue());
		Queue.insetfr(true,"FR","5","UP","337",Queue.getQueue());
		Queue.inseter(true,"ER","5","337",Queue.getQueue());
		Queue.inseter(true,"ER","8","338",Queue.getQueue());
		Queue.insetfr(true,"FR","10","UP","341",Queue.getQueue());
		Queue.inseter(true,"ER","10","341",Queue.getQueue());
		Queue.insetfr(true,"FR","6","UP","348",Queue.getQueue());
		Queue.inseter(true,"ER","6","348",Queue.getQueue());
		Queue.insetfr(true,"FR","6","DOWN","351",Queue.getQueue());
		Queue.inseter(true,"ER","6","351",Queue.getQueue());
		Queue.inseter(true,"ER","3","352",Queue.getQueue());
		Queue.insetfr(true,"FR","9","UP","355",Queue.getQueue());
		Queue.inseter(true,"ER","9","355",Queue.getQueue());
		Queue.insetfr(true,"FR","2","UP","355",Queue.getQueue());
		Queue.inseter(true,"ER","2","355",Queue.getQueue());
		Queue.inseter(true,"ER","5","357",Queue.getQueue());
		Queue.insetfr(true,"FR","2","UP","362",Queue.getQueue());
		Queue.inseter(true,"ER","2","362",Queue.getQueue());
		Queue.insetfr(true,"FR","1","UP","365",Queue.getQueue());
		Queue.inseter(true,"ER","1","365",Queue.getQueue());
		Queue.inseter(true,"ER","2","368",Queue.getQueue());
		Queue.insetfr(true,"FR","7","DOWN","371",Queue.getQueue());
		Queue.inseter(true,"ER","7","371",Queue.getQueue());
		Queue.insetfr(true,"FR","5","UP","373",Queue.getQueue());
		Queue.inseter(true,"ER","5","373",Queue.getQueue());
		Queue.insetfr(true,"FR","4","DOWN","376",Queue.getQueue());
		Queue.inseter(true,"ER","4","376",Queue.getQueue());
		Queue.inseter(true,"ER","10","377",Queue.getQueue());
		Queue.insetfr(true,"FR","2","DOWN","378",Queue.getQueue());
		Queue.inseter(true,"ER","2","378",Queue.getQueue());
		Queue.inseter(true,"ER","5","378",Queue.getQueue());
		Queue.insetfr(true,"FR","5","DOWN","378",Queue.getQueue());
		Queue.inseter(true,"ER","5","378",Queue.getQueue());
		Queue.inseter(true,"ER","9","381",Queue.getQueue());
		Queue.insetfr(true,"FR","10","UP","381",Queue.getQueue());
		Queue.inseter(true,"ER","10","381",Queue.getQueue());
		Queue.insetfr(true,"FR","10","DOWN","381",Queue.getQueue());
		Queue.inseter(true,"ER","10","381",Queue.getQueue());
		Queue.insetfr(true,"FR","7","DOWN","382",Queue.getQueue());
		Queue.inseter(true,"ER","7","382",Queue.getQueue());
		Queue.insetfr(true,"FR","2","UP","382",Queue.getQueue());
		Queue.inseter(true,"ER","2","382",Queue.getQueue());
		Queue.inseter(true,"ER","1","384",Queue.getQueue());
		Queue.insetfr(true,"FR","7","UP","384",Queue.getQueue());
		Queue.inseter(true,"ER","7","384",Queue.getQueue());
		Queue.inseter(true,"ER","6","385",Queue.getQueue());
		Queue.insetfr(true,"FR","6","UP","386",Queue.getQueue());
		Queue.inseter(true,"ER","6","386",Queue.getQueue());
		Queue.insetfr(true,"FR","3","DOWN","387",Queue.getQueue());
		Queue.inseter(true,"ER","3","387",Queue.getQueue());
		Queue.insetfr(true,"FR","7","UP","389",Queue.getQueue());
		Queue.inseter(true,"ER","7","389",Queue.getQueue());
		Queue.inseter(true,"ER","8","390",Queue.getQueue());
		Queue.inseter(true,"ER","3","391",Queue.getQueue());
		Queue.inseter(true,"ER","6","393",Queue.getQueue());
		Queue.inseter(true,"ER","3","393",Queue.getQueue());
		Queue.insetfr(true,"FR","10","UP","394",Queue.getQueue());
		Queue.inseter(true,"ER","10","394",Queue.getQueue());
		Queue.inseter(true,"ER","9","394",Queue.getQueue());
		Queue.inseter(true,"ER","3","395",Queue.getQueue());
		Queue.insetfr(true,"FR","10","UP","395",Queue.getQueue());
		Queue.inseter(true,"ER","10","395",Queue.getQueue());
		Queue.inseter(true,"ER","5","395",Queue.getQueue());
		Queue.insetfr(true,"FR","2","DOWN","399",Queue.getQueue());
		Queue.inseter(true,"ER","2","399",Queue.getQueue());
		Queue.inseter(true,"ER","3","402",Queue.getQueue());
		Queue.insetfr(true,"FR","2","UP","402",Queue.getQueue());
		Queue.inseter(true,"ER","2","402",Queue.getQueue());
		Queue.inseter(true,"ER","5","403",Queue.getQueue());
		Queue.insetfr(true,"FR","6","DOWN","405",Queue.getQueue());
		Queue.inseter(true,"ER","6","405",Queue.getQueue());
		Queue.insetfr(true,"FR","2","UP","405",Queue.getQueue());
		Queue.inseter(true,"ER","2","405",Queue.getQueue());
		Queue.inseter(true,"ER","7","407",Queue.getQueue());
		Queue.insetfr(true,"FR","5","DOWN","408",Queue.getQueue());
		Queue.inseter(true,"ER","5","408",Queue.getQueue());
		Queue.inseter(true,"ER","10","409",Queue.getQueue());
		Queue.insetfr(true,"FR","8","UP","410",Queue.getQueue());
		Queue.inseter(true,"ER","8","410",Queue.getQueue());
		Queue.inseter(true,"ER","2","412",Queue.getQueue());
		Queue.insetfr(true,"FR","8","DOWN","412",Queue.getQueue());
		Queue.inseter(true,"ER","8","412",Queue.getQueue());
		Queue.inseter(true,"ER","7","415",Queue.getQueue());
		Queue.insetfr(true,"FR","4","UP","417",Queue.getQueue());
		Queue.inseter(true,"ER","4","417",Queue.getQueue());
		Queue.inseter(true,"ER","6","417",Queue.getQueue());
		Queue.insetfr(true,"FR","8","DOWN","419",Queue.getQueue());
		Queue.inseter(true,"ER","8","419",Queue.getQueue());
		Queue.insetfr(true,"FR","7","DOWN","420",Queue.getQueue());
		Queue.inseter(true,"ER","7","420",Queue.getQueue());
		Queue.insetfr(true,"FR","3","DOWN","422",Queue.getQueue());
		Queue.inseter(true,"ER","3","422",Queue.getQueue());
		Queue.inseter(true,"ER","7","422",Queue.getQueue());
		Queue.insetfr(true,"FR","7","UP","423",Queue.getQueue());
		Queue.inseter(true,"ER","7","423",Queue.getQueue());
		Queue.insetfr(true,"FR","6","DOWN","425",Queue.getQueue());
		Queue.inseter(true,"ER","6","425",Queue.getQueue());
		Queue.inseter(true,"ER","1","427",Queue.getQueue());
		Queue.insetfr(true,"FR","7","UP","431",Queue.getQueue());
		Queue.inseter(true,"ER","7","431",Queue.getQueue());
		Queue.insetfr(true,"FR","6","DOWN","431",Queue.getQueue());
		Queue.inseter(true,"ER","6","431",Queue.getQueue());
		Queue.insetfr(true,"FR","8","DOWN","436",Queue.getQueue());
		Queue.inseter(true,"ER","8","436",Queue.getQueue());
		Queue.inseter(true,"ER","1","439",Queue.getQueue());
		Queue.inseter(true,"ER","8","439",Queue.getQueue());
		Queue.inseter(true,"ER","9","441",Queue.getQueue());
		Queue.inseter(true,"ER","1","443",Queue.getQueue());
		Queue.inseter(true,"ER","7","444",Queue.getQueue());
		Queue.inseter(true,"ER","3","445",Queue.getQueue());
		Queue.inseter(true,"ER","2","445",Queue.getQueue());
		Queue.insetfr(true,"FR","6","DOWN","445",Queue.getQueue());
		Queue.inseter(true,"ER","6","445",Queue.getQueue());
		Queue.insetfr(true,"FR","2","DOWN","445",Queue.getQueue());
		Queue.inseter(true,"ER","2","445",Queue.getQueue());
		Queue.insetfr(true,"FR","6","UP","446",Queue.getQueue());
		Queue.inseter(true,"ER","6","446",Queue.getQueue());
		Queue.inseter(true,"ER","9","448",Queue.getQueue());
		Queue.insetfr(true,"FR","7","UP","450",Queue.getQueue());
		Queue.inseter(true,"ER","7","450",Queue.getQueue());
		Queue.insetfr(true,"FR","5","DOWN","450",Queue.getQueue());
		Queue.inseter(true,"ER","5","450",Queue.getQueue());
		Queue.insetfr(true,"FR","6","DOWN","454",Queue.getQueue());
		Queue.inseter(true,"ER","6","454",Queue.getQueue());
		Queue.inseter(true,"ER","7","454",Queue.getQueue());
		Queue.insetfr(true,"FR","8","DOWN","457",Queue.getQueue());
		Queue.inseter(true,"ER","8","457",Queue.getQueue());
		Queue.inseter(true,"ER","8","460",Queue.getQueue());
		Queue.insetfr(true,"FR","4","UP","460",Queue.getQueue());
		Queue.inseter(true,"ER","4","460",Queue.getQueue());
		Queue.insetfr(true,"FR","6","UP","461",Queue.getQueue());
		Queue.inseter(true,"ER","6","461",Queue.getQueue());
		Queue.inseter(true,"ER","1","461",Queue.getQueue());
		Queue.inseter(true,"ER","9","463",Queue.getQueue());
		Queue.insetfr(true,"FR","3","DOWN","465",Queue.getQueue());
		Queue.inseter(true,"ER","3","465",Queue.getQueue());
		Queue.insetfr(true,"FR","8","UP","467",Queue.getQueue());
		Queue.inseter(true,"ER","8","467",Queue.getQueue());
		Queue.insetfr(true,"FR","7","DOWN","469",Queue.getQueue());
		Queue.inseter(true,"ER","7","469",Queue.getQueue());
		Queue.inseter(true,"ER","4","471",Queue.getQueue());
		Queue.insetfr(true,"FR","1","UP","474",Queue.getQueue());
		Queue.inseter(true,"ER","1","474",Queue.getQueue());
		Queue.insetfr(true,"FR","8","UP","475",Queue.getQueue());
		Queue.inseter(true,"ER","8","475",Queue.getQueue());
		Queue.insetfr(true,"FR","4","DOWN","480",Queue.getQueue());
		Queue.inseter(true,"ER","4","480",Queue.getQueue());
		Queue.inseter(true,"ER","1","481",Queue.getQueue());
		Queue.insetfr(true,"FR","6","UP","484",Queue.getQueue());
		Queue.inseter(true,"ER","6","484",Queue.getQueue());
		Queue.inseter(true,"ER","2","485",Queue.getQueue());
		Queue.insetfr(true,"FR","8","UP","487",Queue.getQueue());
		Queue.inseter(true,"ER","8","487",Queue.getQueue());
		Queue.insetfr(true,"FR","5","DOWN","489",Queue.getQueue());
		Queue.inseter(true,"ER","5","489",Queue.getQueue());
		Queue.inseter(true,"ER","9","489",Queue.getQueue());
		Queue.inseter(true,"ER","5","489",Queue.getQueue());
		Queue.insetfr(true,"FR","5","DOWN","490",Queue.getQueue());
		Queue.inseter(true,"ER","5","490",Queue.getQueue());
		Queue.inseter(true,"ER","8","493",Queue.getQueue());
		Queue.inseter(true,"ER","8","497",Queue.getQueue());
		Queue.insetfr(true,"FR","6","DOWN","500",Queue.getQueue());
		Queue.inseter(true,"ER","6","500",Queue.getQueue());
		Queue.insetfr(true,"FR","5","UP","500",Queue.getQueue());
		Queue.inseter(true,"ER","5","500",Queue.getQueue());
		Queue.inseter(true,"ER","8","502",Queue.getQueue());
		Queue.inseter(true,"ER","8","504",Queue.getQueue());
		Queue.insetfr(true,"FR","8","UP","504",Queue.getQueue());
		Queue.inseter(true,"ER","8","504",Queue.getQueue());
		Queue.inseter(true,"ER","8","505",Queue.getQueue());
		Queue.insetfr(true,"FR","6","DOWN","508",Queue.getQueue());
		Queue.inseter(true,"ER","6","508",Queue.getQueue());
		Queue.insetfr(true,"FR","10","DOWN","509",Queue.getQueue());
		Queue.inseter(true,"ER","10","509",Queue.getQueue());
		Queue.insetfr(true,"FR","9","DOWN","510",Queue.getQueue());
		Queue.inseter(true,"ER","9","510",Queue.getQueue());
		Queue.inseter(true,"ER","7","510",Queue.getQueue());
		Queue.inseter(true,"ER","4","512",Queue.getQueue());
		Queue.inseter(true,"ER","3","513",Queue.getQueue());
		Queue.inseter(true,"ER","4","514",Queue.getQueue());
		Queue.inseter(true,"ER","4","515",Queue.getQueue());
		Queue.insetfr(true,"FR","6","DOWN","515",Queue.getQueue());
		Queue.inseter(true,"ER","6","515",Queue.getQueue());
		Queue.inseter(true,"ER","3","518",Queue.getQueue());
		Queue.inseter(true,"ER","10","518",Queue.getQueue());
		Queue.insetfr(true,"FR","7","DOWN","521",Queue.getQueue());
		Queue.inseter(true,"ER","7","521",Queue.getQueue());
		Queue.inseter(true,"ER","10","521",Queue.getQueue());
		Queue.inseter(true,"ER","6","521",Queue.getQueue());
		Queue.inseter(true,"ER","8","523",Queue.getQueue());
		Queue.inseter(true,"ER","1","524",Queue.getQueue());
		Queue.inseter(true,"ER","6","526",Queue.getQueue());
		Queue.inseter(true,"ER","10","529",Queue.getQueue());
		Queue.inseter(true,"ER","9","531",Queue.getQueue());
		Queue.inseter(true,"ER","6","533",Queue.getQueue());
		Queue.inseter(true,"ER","1","533",Queue.getQueue());
		Queue.inseter(true,"ER","5","535",Queue.getQueue());
		Queue.inseter(true,"ER","6","535",Queue.getQueue());
		Queue.insetfr(true,"FR","8","DOWN","538",Queue.getQueue());
		Queue.inseter(true,"ER","8","538",Queue.getQueue());
		Queue.inseter(true,"ER","10","540",Queue.getQueue());
		Queue.insetfr(true,"FR","4","UP","540",Queue.getQueue());
		Queue.inseter(true,"ER","4","540",Queue.getQueue());
		Queue.inseter(true,"ER","8","543",Queue.getQueue());
		Queue.inseter(true,"ER","4","544",Queue.getQueue());
		Queue.insetfr(true,"FR","6","UP","546",Queue.getQueue());
		Queue.inseter(true,"ER","6","546",Queue.getQueue());
		Queue.insetfr(true,"FR","4","UP","548",Queue.getQueue());
		Queue.inseter(true,"ER","4","548",Queue.getQueue());
		Queue.insetfr(true,"FR","4","DOWN","549",Queue.getQueue());
		Queue.inseter(true,"ER","4","549",Queue.getQueue());
		Queue.inseter(true,"ER","2","551",Queue.getQueue());
		Queue.insetfr(true,"FR","2","DOWN","551",Queue.getQueue());
		Queue.inseter(true,"ER","2","551",Queue.getQueue());
		Queue.inseter(true,"ER","2","554",Queue.getQueue());
		Queue.insetfr(true,"FR","8","DOWN","555",Queue.getQueue());
		Queue.inseter(true,"ER","8","555",Queue.getQueue());
		Queue.inseter(true,"ER","4","556",Queue.getQueue());
		Queue.inseter(true,"ER","7","557",Queue.getQueue());
		Queue.insetfr(true,"FR","3","UP","557",Queue.getQueue());
		Queue.inseter(true,"ER","3","557",Queue.getQueue());
		Queue.inseter(true,"ER","7","558",Queue.getQueue());
		Queue.inseter(true,"ER","2","559",Queue.getQueue());
		Queue.insetfr(true,"FR","9","UP","559",Queue.getQueue());
		Queue.inseter(true,"ER","9","559",Queue.getQueue());
		Queue.insetfr(true,"FR","8","DOWN","559",Queue.getQueue());
		Queue.inseter(true,"ER","8","559",Queue.getQueue());
		Queue.insetfr(true,"FR","8","UP","562",Queue.getQueue());
		Queue.inseter(true,"ER","8","562",Queue.getQueue());
		Queue.inseter(true,"ER","1","563",Queue.getQueue());
		Queue.inseter(true,"ER","6","563",Queue.getQueue());
		Queue.inseter(true,"ER","1","566",Queue.getQueue());
		Queue.inseter(true,"ER","10","568",Queue.getQueue());
		Queue.inseter(true,"ER","5","570",Queue.getQueue());
		Queue.insetfr(true,"FR","6","DOWN","571",Queue.getQueue());
		Queue.inseter(true,"ER","6","571",Queue.getQueue());
		Queue.inseter(true,"ER","10","573",Queue.getQueue());
		Queue.inseter(true,"ER","7","576",Queue.getQueue());
		Queue.inseter(true,"ER","6","576",Queue.getQueue());
		Queue.inseter(true,"ER","3","577",Queue.getQueue());
		Queue.insetfr(true,"FR","7","UP","578",Queue.getQueue());
		Queue.inseter(true,"ER","7","578",Queue.getQueue());
		Queue.insetfr(true,"FR","3","UP","580",Queue.getQueue());
		Queue.inseter(true,"ER","3","580",Queue.getQueue());
		Queue.insetfr(true,"FR","3","DOWN","580",Queue.getQueue());
		Queue.inseter(true,"ER","3","580",Queue.getQueue());
		Queue.insetfr(true,"FR","8","UP","580",Queue.getQueue());
		Queue.inseter(true,"ER","8","580",Queue.getQueue());
		Queue.insetfr(true,"FR","10","UP","580",Queue.getQueue());
		Queue.inseter(true,"ER","10","580",Queue.getQueue());
		Queue.insetfr(true,"FR","2","DOWN","583",Queue.getQueue());
		Queue.inseter(true,"ER","2","583",Queue.getQueue());
		Queue.insetfr(true,"FR","4","DOWN","583",Queue.getQueue());
		Queue.inseter(true,"ER","4","583",Queue.getQueue());
		Queue.inseter(true,"ER","4","584",Queue.getQueue());
		Queue.insetfr(true,"FR","10","DOWN","590",Queue.getQueue());
		Queue.inseter(true,"ER","10","590",Queue.getQueue());
		Queue.insetfr(true,"FR","10","UP","590",Queue.getQueue());
		Queue.inseter(true,"ER","10","590",Queue.getQueue());
		Queue.insetfr(true,"FR","5","DOWN","593",Queue.getQueue());
		Queue.inseter(true,"ER","5","593",Queue.getQueue());
		Queue.insetfr(true,"FR","10","DOWN","595",Queue.getQueue());
		Queue.inseter(true,"ER","10","595",Queue.getQueue());
		Queue.inseter(true,"ER","8","597",Queue.getQueue());
		Queue.inseter(true,"ER","9","598",Queue.getQueue());
		Queue.inseter(true,"ER","2","599",Queue.getQueue());
		Queue.insetfr(true,"FR","1","UP","602",Queue.getQueue());
		Queue.inseter(true,"ER","1","602",Queue.getQueue());
		Queue.insetfr(true,"FR","10","DOWN","605",Queue.getQueue());
		Queue.inseter(true,"ER","10","605",Queue.getQueue());
		Queue.insetfr(true,"FR","7","DOWN","605",Queue.getQueue());
		Queue.inseter(true,"ER","7","605",Queue.getQueue());
		Queue.insetfr(true,"FR","4","DOWN","606",Queue.getQueue());
		Queue.inseter(true,"ER","4","606",Queue.getQueue());
		Queue.inseter(true,"ER","1","606",Queue.getQueue());
		Queue.inseter(true,"ER","4","606",Queue.getQueue());
		Queue.inseter(true,"ER","9","608",Queue.getQueue());
		Queue.insetfr(true,"FR","9","DOWN","611",Queue.getQueue());
		Queue.inseter(true,"ER","9","611",Queue.getQueue());
		Queue.insetfr(true,"FR","10","UP","611",Queue.getQueue());
		Queue.inseter(true,"ER","10","611",Queue.getQueue());
		Queue.inseter(true,"ER","5","618",Queue.getQueue());
		Queue.insetfr(true,"FR","7","DOWN","619",Queue.getQueue());
		Queue.inseter(true,"ER","7","619",Queue.getQueue());
		Queue.inseter(true,"ER","8","625",Queue.getQueue());
		Queue.inseter(true,"ER","7","631",Queue.getQueue());
		Queue.inseter(true,"ER","1","634",Queue.getQueue());
		Queue.insetfr(true,"FR","4","DOWN","635",Queue.getQueue());
		Queue.inseter(true,"ER","4","635",Queue.getQueue());
		Queue.insetfr(true,"FR","2","DOWN","637",Queue.getQueue());
		Queue.inseter(true,"ER","2","637",Queue.getQueue());
		Queue.insetfr(true,"FR","10","UP","639",Queue.getQueue());
		Queue.inseter(true,"ER","10","639",Queue.getQueue());
		Queue.inseter(true,"ER","7","644",Queue.getQueue());
		Queue.insetfr(true,"FR","4","DOWN","645",Queue.getQueue());
		Queue.inseter(true,"ER","4","645",Queue.getQueue());
		Queue.insetfr(true,"FR","3","DOWN","645",Queue.getQueue());
		Queue.inseter(true,"ER","3","645",Queue.getQueue());
		Queue.inseter(true,"ER","1","647",Queue.getQueue());
		Queue.insetfr(true,"FR","3","DOWN","648",Queue.getQueue());
		Queue.inseter(true,"ER","3","648",Queue.getQueue());
		Queue.insetfr(true,"FR","5","UP","649",Queue.getQueue());
		Queue.inseter(true,"ER","5","649",Queue.getQueue());
		Queue.insetfr(true,"FR","6","UP","649",Queue.getQueue());
		Queue.inseter(true,"ER","6","649",Queue.getQueue());
		Queue.insetfr(true,"FR","6","UP","652",Queue.getQueue());
		Queue.inseter(true,"ER","6","652",Queue.getQueue());
		Queue.inseter(true,"ER","10","654",Queue.getQueue());
		Queue.inseter(true,"ER","6","656",Queue.getQueue());
		Queue.insetfr(true,"FR","10","UP","658",Queue.getQueue());
		Queue.inseter(true,"ER","10","658",Queue.getQueue());
		Queue.insetfr(true,"FR","4","UP","659",Queue.getQueue());
		Queue.inseter(true,"ER","4","659",Queue.getQueue());
		Queue.inseter(true,"ER","9","662",Queue.getQueue());
		Queue.inseter(true,"ER","2","664",Queue.getQueue());
		Queue.inseter(true,"ER","1","667",Queue.getQueue());
		Queue.insetfr(true,"FR","1","UP","668",Queue.getQueue());
		Queue.inseter(true,"ER","1","668",Queue.getQueue());
		Queue.inseter(true,"ER","2","668",Queue.getQueue());
		Queue.inseter(true,"ER","10","671",Queue.getQueue());
		Queue.inseter(true,"ER","7","672",Queue.getQueue());
		Queue.inseter(true,"ER","6","677",Queue.getQueue());
		Queue.inseter(true,"ER","10","678",Queue.getQueue());
		Queue.inseter(true,"ER","5","679",Queue.getQueue());
		Queue.inseter(true,"ER","4","683",Queue.getQueue());
		Queue.insetfr(true,"FR","7","DOWN","684",Queue.getQueue());
		Queue.inseter(true,"ER","7","684",Queue.getQueue());
		Queue.insetfr(true,"FR","8","UP","687",Queue.getQueue());
		Queue.inseter(true,"ER","8","687",Queue.getQueue());
		Queue.inseter(true,"ER","2","687",Queue.getQueue());
		Queue.insetfr(true,"FR","3","DOWN","690",Queue.getQueue());
		Queue.inseter(true,"ER","3","690",Queue.getQueue());
		Queue.insetfr(true,"FR","7","DOWN","692",Queue.getQueue());
		Queue.inseter(true,"ER","7","692",Queue.getQueue());
		Queue.inseter(true,"ER","10","694",Queue.getQueue());
		Queue.inseter(true,"ER","3","696",Queue.getQueue());
		Queue.inseter(true,"ER","1","696",Queue.getQueue());
		Queue.insetfr(true,"FR","3","UP","697",Queue.getQueue());
		Queue.inseter(true,"ER","3","697",Queue.getQueue());
		Queue.insetfr(true,"FR","7","UP","700",Queue.getQueue());
		Queue.inseter(true,"ER","7","700",Queue.getQueue());
		Queue.insetfr(true,"FR","4","DOWN","703",Queue.getQueue());
		Queue.inseter(true,"ER","4","703",Queue.getQueue());
		Queue.inseter(true,"ER","2","705",Queue.getQueue());
		Queue.inseter(true,"ER","9","705",Queue.getQueue());
		Queue.inseter(true,"ER","4","708",Queue.getQueue());
		Queue.insetfr(true,"FR","5","UP","711",Queue.getQueue());
		Queue.inseter(true,"ER","5","711",Queue.getQueue());
		Queue.insetfr(true,"FR","2","DOWN","713",Queue.getQueue());
		Queue.inseter(true,"ER","2","713",Queue.getQueue());
		Queue.inseter(true,"ER","3","716",Queue.getQueue());
		Queue.insetfr(true,"FR","5","DOWN","719",Queue.getQueue());
		Queue.inseter(true,"ER","5","719",Queue.getQueue());
		Queue.insetfr(true,"FR","10","DOWN","721",Queue.getQueue());
		Queue.inseter(true,"ER","10","721",Queue.getQueue());
		Queue.inseter(true,"ER","4","722",Queue.getQueue());
		Queue.inseter(true,"ER","3","723",Queue.getQueue());
		Queue.insetfr(true,"FR","9","DOWN","723",Queue.getQueue());
		Queue.inseter(true,"ER","9","723",Queue.getQueue());
		Queue.inseter(true,"ER","4","723",Queue.getQueue());
		Queue.inseter(true,"ER","3","725",Queue.getQueue());
		Queue.insetfr(true,"FR","10","UP","728",Queue.getQueue());
		Queue.inseter(true,"ER","10","728",Queue.getQueue());
		Queue.inseter(true,"ER","1","730",Queue.getQueue());
		Queue.insetfr(true,"FR","8","DOWN","731",Queue.getQueue());
		Queue.inseter(true,"ER","8","731",Queue.getQueue());
		Queue.insetfr(true,"FR","10","DOWN","736",Queue.getQueue());
		Queue.inseter(true,"ER","10","736",Queue.getQueue());
		Queue.inseter(true,"ER","10","738",Queue.getQueue());
		Queue.inseter(true,"ER","7","740",Queue.getQueue());
		Queue.insetfr(true,"FR","3","DOWN","740",Queue.getQueue());
		Queue.inseter(true,"ER","3","740",Queue.getQueue());
		Queue.inseter(true,"ER","2","743",Queue.getQueue());
		Queue.inseter(true,"ER","10","743",Queue.getQueue());
		Queue.inseter(true,"ER","10","744",Queue.getQueue());
		Queue.insetfr(true,"FR","6","DOWN","745",Queue.getQueue());
		Queue.inseter(true,"ER","6","745",Queue.getQueue());
		Queue.inseter(true,"ER","3","747",Queue.getQueue());
		Queue.inseter(true,"ER","1","749",Queue.getQueue());
		Queue.insetfr(true,"FR","9","UP","750",Queue.getQueue());
		Queue.inseter(true,"ER","9","750",Queue.getQueue());
		Queue.inseter(true,"ER","3","751",Queue.getQueue());
		Queue.inseter(true,"ER","9","753",Queue.getQueue());
		Queue.inseter(true,"ER","7","756",Queue.getQueue());
		Queue.inseter(true,"ER","7","758",Queue.getQueue());
		Queue.insetfr(true,"FR","10","DOWN","761",Queue.getQueue());
		Queue.inseter(true,"ER","10","761",Queue.getQueue());
		Queue.insetfr(true,"FR","9","DOWN","764",Queue.getQueue());
		Queue.inseter(true,"ER","9","764",Queue.getQueue());
		Queue.inseter(true,"ER","7","767",Queue.getQueue());
		Queue.inseter(true,"ER","8","768",Queue.getQueue());
		Queue.insetfr(true,"FR","9","DOWN","771",Queue.getQueue());
		Queue.inseter(true,"ER","9","771",Queue.getQueue());
		Queue.inseter(true,"ER","9","774",Queue.getQueue());
		Queue.insetfr(true,"FR","2","DOWN","777",Queue.getQueue());
		Queue.inseter(true,"ER","2","777",Queue.getQueue());
		Queue.inseter(true,"ER","4","778",Queue.getQueue());
		Queue.inseter(true,"ER","2","779",Queue.getQueue());
		Queue.insetfr(true,"FR","10","UP","782",Queue.getQueue());
		Queue.inseter(true,"ER","10","782",Queue.getQueue());
		Queue.inseter(true,"ER","9","783",Queue.getQueue());
		Queue.inseter(true,"ER","6","784",Queue.getQueue());
		Queue.insetfr(true,"FR","4","DOWN","785",Queue.getQueue());
		Queue.inseter(true,"ER","4","785",Queue.getQueue());
		Queue.inseter(true,"ER","4","785",Queue.getQueue());
		Queue.inseter(true,"ER","10","787",Queue.getQueue());
		Queue.inseter(true,"ER","7","788",Queue.getQueue());
		Queue.inseter(true,"ER","9","789",Queue.getQueue());
		Queue.inseter(true,"ER","2","789",Queue.getQueue());
		Queue.insetfr(true,"FR","5","DOWN","790",Queue.getQueue());
		Queue.inseter(true,"ER","5","790",Queue.getQueue());
		Queue.insetfr(true,"FR","9","DOWN","790",Queue.getQueue());
		Queue.inseter(true,"ER","9","790",Queue.getQueue());
		Queue.inseter(true,"ER","9","791",Queue.getQueue());
		Queue.inseter(true,"ER","8","794",Queue.getQueue());
		Queue.insetfr(true,"FR","5","DOWN","796",Queue.getQueue());
		Queue.inseter(true,"ER","5","796",Queue.getQueue());
		Queue.inseter(true,"ER","3","799",Queue.getQueue());
		Queue.insetfr(true,"FR","6","DOWN","802",Queue.getQueue());
		Queue.inseter(true,"ER","6","802",Queue.getQueue());
		Queue.insetfr(true,"FR","5","DOWN","805",Queue.getQueue());
		Queue.inseter(true,"ER","5","805",Queue.getQueue());
		Queue.insetfr(true,"FR","9","UP","805",Queue.getQueue());
		Queue.inseter(true,"ER","9","805",Queue.getQueue());
		Queue.insetfr(true,"FR","5","DOWN","807",Queue.getQueue());
		Queue.inseter(true,"ER","5","807",Queue.getQueue());
		Queue.inseter(true,"ER","5","811",Queue.getQueue());
		Queue.inseter(true,"ER","1","817",Queue.getQueue());
		Queue.inseter(true,"ER","8","818",Queue.getQueue());
		Queue.insetfr(true,"FR","7","UP","818",Queue.getQueue());
		Queue.inseter(true,"ER","7","818",Queue.getQueue());
		Queue.inseter(true,"ER","3","821",Queue.getQueue());
		Queue.insetfr(true,"FR","4","DOWN","821",Queue.getQueue());
		Queue.inseter(true,"ER","4","821",Queue.getQueue());
		Queue.insetfr(true,"FR","3","UP","821",Queue.getQueue());
		Queue.inseter(true,"ER","3","821",Queue.getQueue());
		Queue.inseter(true,"ER","2","826",Queue.getQueue());
		Queue.inseter(true,"ER","10","828",Queue.getQueue());
		Queue.inseter(true,"ER","6","829",Queue.getQueue());
		Queue.insetfr(true,"FR","8","DOWN","830",Queue.getQueue());
		Queue.inseter(true,"ER","8","830",Queue.getQueue());
		Queue.insetfr(true,"FR","4","DOWN","833",Queue.getQueue());
		Queue.inseter(true,"ER","4","833",Queue.getQueue());
		Queue.inseter(true,"ER","7","834",Queue.getQueue());
		Queue.inseter(true,"ER","7","835",Queue.getQueue());
		Queue.inseter(true,"ER","9","837",Queue.getQueue());
		Queue.inseter(true,"ER","3","840",Queue.getQueue());
		Queue.insetfr(true,"FR","7","DOWN","841",Queue.getQueue());
		Queue.inseter(true,"ER","7","841",Queue.getQueue());
		Queue.inseter(true,"ER","3","844",Queue.getQueue());
		Queue.inseter(true,"ER","2","846",Queue.getQueue());
		Queue.insetfr(true,"FR","7","UP","847",Queue.getQueue());
		Queue.inseter(true,"ER","7","847",Queue.getQueue());
		Queue.inseter(true,"ER","4","850",Queue.getQueue());
		Queue.insetfr(true,"FR","3","UP","855",Queue.getQueue());
		Queue.inseter(true,"ER","3","855",Queue.getQueue());
		Queue.insetfr(true,"FR","4","UP","858",Queue.getQueue());
		Queue.inseter(true,"ER","4","858",Queue.getQueue());
		Queue.inseter(true,"ER","9","861",Queue.getQueue());
		Queue.insetfr(true,"FR","4","DOWN","862",Queue.getQueue());
		Queue.inseter(true,"ER","4","862",Queue.getQueue());
		Queue.inseter(true,"ER","10","864",Queue.getQueue());
		Queue.inseter(true,"ER","8","867",Queue.getQueue());
		Queue.insetfr(true,"FR","2","UP","868",Queue.getQueue());
		Queue.inseter(true,"ER","2","868",Queue.getQueue());
		Queue.inseter(true,"ER","7","870",Queue.getQueue());
		Queue.insetfr(true,"FR","10","DOWN","872",Queue.getQueue());
		Queue.inseter(true,"ER","10","872",Queue.getQueue());
		Queue.inseter(true,"ER","8","874",Queue.getQueue());
		Queue.insetfr(true,"FR","7","DOWN","876",Queue.getQueue());
		Queue.inseter(true,"ER","7","876",Queue.getQueue());
		Queue.insetfr(true,"FR","5","UP","877",Queue.getQueue());
		Queue.inseter(true,"ER","5","877",Queue.getQueue());
		Queue.insetfr(true,"FR","2","DOWN","878",Queue.getQueue());
		Queue.inseter(true,"ER","2","878",Queue.getQueue());
		Queue.inseter(true,"ER","2","880",Queue.getQueue());
		Queue.inseter(true,"ER","6","880",Queue.getQueue());
		Queue.insetfr(true,"FR","9","UP","881",Queue.getQueue());
		Queue.inseter(true,"ER","9","881",Queue.getQueue());
		Queue.insetfr(true,"FR","10","UP","883",Queue.getQueue());
		Queue.inseter(true,"ER","10","883",Queue.getQueue());
		Queue.insetfr(true,"FR","8","UP","885",Queue.getQueue());
		Queue.inseter(true,"ER","8","885",Queue.getQueue());
		Queue.inseter(true,"ER","3","887",Queue.getQueue());
		Queue.inseter(true,"ER","5","888",Queue.getQueue());
		Queue.insetfr(true,"FR","10","UP","890",Queue.getQueue());
		Queue.inseter(true,"ER","10","890",Queue.getQueue());
		Queue.insetfr(true,"FR","9","UP","891",Queue.getQueue());
		Queue.inseter(true,"ER","9","891",Queue.getQueue());
		Queue.insetfr(true,"FR","8","DOWN","893",Queue.getQueue());
		Queue.inseter(true,"ER","8","893",Queue.getQueue());
		Queue.insetfr(true,"FR","3","UP","895",Queue.getQueue());
		Queue.inseter(true,"ER","3","895",Queue.getQueue());
		Queue.insetfr(true,"FR","9","UP","897",Queue.getQueue());
		Queue.inseter(true,"ER","9","897",Queue.getQueue());
		Queue.insetfr(true,"FR","5","DOWN","898",Queue.getQueue());
		Queue.inseter(true,"ER","5","898",Queue.getQueue());
		Queue.inseter(true,"ER","8","902",Queue.getQueue());
		Queue.insetfr(true,"FR","3","UP","904",Queue.getQueue());
		Queue.inseter(true,"ER","3","904",Queue.getQueue());
		Queue.inseter(true,"ER","3","904",Queue.getQueue());
		Queue.insetfr(true,"FR","3","DOWN","907",Queue.getQueue());
		Queue.inseter(true,"ER","3","907",Queue.getQueue());
		Queue.inseter(true,"ER","1","907",Queue.getQueue());
		Queue.inseter(true,"ER","6","908",Queue.getQueue());
		Queue.inseter(true,"ER","1","909",Queue.getQueue());
		Queue.insetfr(true,"FR","9","DOWN","911",Queue.getQueue());
		Queue.inseter(true,"ER","9","911",Queue.getQueue());
		Queue.insetfr(true,"FR","7","UP","914",Queue.getQueue());
		Queue.inseter(true,"ER","7","914",Queue.getQueue());
		Queue.insetfr(true,"FR","8","DOWN","914",Queue.getQueue());
		Queue.inseter(true,"ER","8","914",Queue.getQueue());
		Queue.insetfr(true,"FR","5","UP","914",Queue.getQueue());
		Queue.inseter(true,"ER","5","914",Queue.getQueue());
		Queue.insetfr(true,"FR","5","DOWN","916",Queue.getQueue());
		Queue.inseter(true,"ER","5","916",Queue.getQueue());
		Queue.insetfr(true,"FR","3","DOWN","917",Queue.getQueue());
		Queue.inseter(true,"ER","3","917",Queue.getQueue());
		Queue.inseter(true,"ER","2","920",Queue.getQueue());
		Queue.insetfr(true,"FR","5","UP","923",Queue.getQueue());
		Queue.inseter(true,"ER","5","923",Queue.getQueue());
		Queue.inseter(true,"ER","6","926",Queue.getQueue());
		Queue.insetfr(true,"FR","7","DOWN","926",Queue.getQueue());
		Queue.inseter(true,"ER","7","926",Queue.getQueue());
		Queue.inseter(true,"ER","7","926",Queue.getQueue());
		Queue.insetfr(true,"FR","5","UP","928",Queue.getQueue());
		Queue.inseter(true,"ER","5","928",Queue.getQueue());
		Queue.insetfr(true,"FR","6","DOWN","928",Queue.getQueue());
		Queue.inseter(true,"ER","6","928",Queue.getQueue());
		Queue.inseter(true,"ER","2","930",Queue.getQueue());
		Queue.insetfr(true,"FR","1","UP","932",Queue.getQueue());
		Queue.inseter(true,"ER","1","932",Queue.getQueue());
		Queue.inseter(true,"ER","10","932",Queue.getQueue());
		Queue.inseter(true,"ER","7","932",Queue.getQueue());
		Queue.inseter(true,"ER","3","935",Queue.getQueue());
		Queue.insetfr(true,"FR","2","DOWN","936",Queue.getQueue());
		Queue.inseter(true,"ER","2","936",Queue.getQueue());
		Queue.insetfr(true,"FR","3","UP","937",Queue.getQueue());
		Queue.inseter(true,"ER","3","937",Queue.getQueue());
		Queue.insetfr(true,"FR","9","UP","939",Queue.getQueue());
		Queue.inseter(true,"ER","9","939",Queue.getQueue());
		Queue.inseter(true,"ER","4","941",Queue.getQueue());
		Queue.inseter(true,"ER","3","943",Queue.getQueue());
		Queue.insetfr(true,"FR","7","DOWN","944",Queue.getQueue());
		Queue.inseter(true,"ER","7","944",Queue.getQueue());
		Queue.inseter(true,"ER","7","946",Queue.getQueue());
		Queue.inseter(true,"ER","2","950",Queue.getQueue());
		Queue.insetfr(true,"FR","6","UP","951",Queue.getQueue());
		Queue.inseter(true,"ER","6","951",Queue.getQueue());
		Queue.inseter(true,"ER","8","952",Queue.getQueue());
		Queue.insetfr(true,"FR","4","DOWN","952",Queue.getQueue());
		Queue.inseter(true,"ER","4","952",Queue.getQueue());
		Queue.inseter(true,"ER","2","953",Queue.getQueue());
		Queue.inseter(true,"ER","9","956",Queue.getQueue());
		Queue.inseter(true,"ER","6","959",Queue.getQueue());
		Queue.insetfr(true,"FR","2","UP","961",Queue.getQueue());
		Queue.inseter(true,"ER","2","961",Queue.getQueue());
		Queue.insetfr(true,"FR","5","UP","962",Queue.getQueue());
		Queue.inseter(true,"ER","5","962",Queue.getQueue());
		Queue.insetfr(true,"FR","10","UP","963",Queue.getQueue());
		Queue.inseter(true,"ER","10","963",Queue.getQueue());
		Queue.insetfr(true,"FR","3","UP","966",Queue.getQueue());
		Queue.inseter(true,"ER","3","966",Queue.getQueue());
		Queue.inseter(true,"ER","3","974",Queue.getQueue());
		Queue.insetfr(true,"FR","2","UP","974",Queue.getQueue());
		Queue.inseter(true,"ER","2","974",Queue.getQueue());
		Queue.insetfr(true,"FR","2","UP","978",Queue.getQueue());
		Queue.inseter(true,"ER","2","978",Queue.getQueue());
		Queue.inseter(true,"ER","5","980",Queue.getQueue());
		Queue.inseter(true,"ER","5","983",Queue.getQueue());
		Queue.insetfr(true,"FR","6","UP","986",Queue.getQueue());
		Queue.inseter(true,"ER","6","986",Queue.getQueue());
		Queue.insetfr(true,"FR","6","UP","988",Queue.getQueue());
		Queue.inseter(true,"ER","6","988",Queue.getQueue());
		Queue.insetfr(true,"FR","2","UP","989",Queue.getQueue());
		Queue.inseter(true,"ER","2","989",Queue.getQueue());
		Queue.insetfr(true,"FR","3","UP","990",Queue.getQueue());
		Queue.inseter(true,"ER","3","990",Queue.getQueue());
		Queue.insetfr(true,"FR","10","UP","993",Queue.getQueue());
		Queue.inseter(true,"ER","10","993",Queue.getQueue());
		Queue.insetfr(true,"FR","3","UP","994",Queue.getQueue());
		Queue.inseter(true,"ER","3","994",Queue.getQueue());
		Queue.inseter(true,"ER","2","997",Queue.getQueue());
		Queue.inseter(true,"ER","3","999",Queue.getQueue());
		Queue.insetfr(true,"FR","6","DOWN","1000",Queue.getQueue());
		Queue.inseter(true,"ER","6","1000",Queue.getQueue());
		Queue.inseter(true,"ER","7","1002",Queue.getQueue());
		Queue.insetfr(true,"FR","6","DOWN","1002",Queue.getQueue());
		Queue.inseter(true,"ER","6","1002",Queue.getQueue());
		Queue.inseter(true,"ER","5","1003",Queue.getQueue());
		Queue.insetfr(true,"FR","7","DOWN","1003",Queue.getQueue());
		Queue.inseter(true,"ER","7","1003",Queue.getQueue());
		Queue.insetfr(true,"FR","3","UP","1005",Queue.getQueue());
		Queue.inseter(true,"ER","3","1005",Queue.getQueue());
		Queue.inseter(true,"ER","4","1006",Queue.getQueue());
		Queue.inseter(true,"ER","9","1009",Queue.getQueue());
		Queue.insetfr(true,"FR","8","DOWN","1012",Queue.getQueue());
		Queue.inseter(true,"ER","8","1012",Queue.getQueue());
		Queue.inseter(true,"ER","6","1013",Queue.getQueue());
		Queue.inseter(true,"ER","6","1015",Queue.getQueue());
		Queue.inseter(true,"ER","10","1017",Queue.getQueue());
		Queue.insetfr(true,"FR","4","UP","1019",Queue.getQueue());
		Queue.inseter(true,"ER","4","1019",Queue.getQueue());
		Queue.inseter(true,"ER","5","1020",Queue.getQueue());
		Queue.insetfr(true,"FR","5","UP","1023",Queue.getQueue());
		Queue.inseter(true,"ER","5","1023",Queue.getQueue());
		Queue.insetfr(true,"FR","5","DOWN","1024",Queue.getQueue());
		Queue.inseter(true,"ER","5","1024",Queue.getQueue());
		Queue.inseter(true,"ER","5","1025",Queue.getQueue());
		Queue.insetfr(true,"FR","6","UP","1029",Queue.getQueue());
		Queue.inseter(true,"ER","6","1029",Queue.getQueue());
		Queue.insetfr(true,"FR","1","UP","1030",Queue.getQueue());
		Queue.inseter(true,"ER","1","1030",Queue.getQueue());
		Queue.inseter(true,"ER","7","1032",Queue.getQueue());
		Queue.insetfr(true,"FR","8","DOWN","1032",Queue.getQueue());
		Queue.inseter(true,"ER","8","1032",Queue.getQueue());
		Queue.inseter(true,"ER","4","1034",Queue.getQueue());
		Queue.inseter(true,"ER","6","1036",Queue.getQueue());
		Queue.inseter(true,"ER","10","1039",Queue.getQueue());
		Queue.inseter(true,"ER","9","1040",Queue.getQueue());
		
		Queue.inseter(true,"ER","10","5000",Queue.getQueue());
		Queue.inseter(true,"ER","1","5000.5",Queue.getQueue());
		Queue.inseter(true,"ER","9","5000.5",Queue.getQueue());
		Queue.inseter(true,"ER","9","5001",Queue.getQueue());
		Queue.inseter(true,"ER","9","5001.5",Queue.getQueue());		
		Queue.inseter(true,"ER","9","5002",Queue.getQueue());
		
		Queue.inseter(true,"ER","1","5000",Queue.getQueue());
		Queue.inseter(true,"ER","10","5000.5",Queue.getQueue());
		Queue.inseter(true,"ER","2","5000.5",Queue.getQueue());
		Queue.inseter(true,"ER","2","5001",Queue.getQueue());
		Queue.inseter(true,"ER","2","5001.5",Queue.getQueue());		
		Queue.inseter(true,"ER","2","5002",Queue.getQueue());
		

		NewElevator.run(Queue.getQueue());
		
		setUp();
		Queue.insetfr(true, "FR", "1","UP", "0", Queue.getQueue());
		Queue.insetfr(true, "FR", "10","DOWN", "0", Queue.getQueue());
		Queue.insetfr(true, "FR", "2","UP", "0", Queue.getQueue());
		Queue.insetfr(true, "FR", "2","UP", "0.5", Queue.getQueue());
		Queue.insetfr(true, "FR", "2","UP", "1", Queue.getQueue());
		Queue.insetfr(true, "FR", "2","UP", "1.5", Queue.getQueue());
		Queue.insetfr(true, "FR", "2","UP", "2", Queue.getQueue());
		Queue.insetfr(true, "FR", "2","UP", "2.5", Queue.getQueue());
		Queue.insetfr(true, "FR", "2","UP", "3", Queue.getQueue());
		
		Queue.insetfr(true, "FR", "3","UP", "0", Queue.getQueue());
		Queue.insetfr(true, "FR", "3","UP", "0.5", Queue.getQueue());
		Queue.insetfr(true, "FR", "3","UP", "1", Queue.getQueue());
		Queue.insetfr(true, "FR", "3","UP", "1.5", Queue.getQueue());
		Queue.insetfr(true, "FR", "3","UP", "2", Queue.getQueue());
		Queue.insetfr(true, "FR", "3","UP", "2.5", Queue.getQueue());
		Queue.insetfr(true, "FR", "3","UP", "3", Queue.getQueue());
		
		

		Queue.insetfr(true, "FR", "2","DOWN", "100", Queue.getQueue());
		Queue.insetfr(true, "FR", "9","DOWN", "100", Queue.getQueue());
		Queue.insetfr(true, "FR", "9","DOWN", "100.5", Queue.getQueue());
		Queue.insetfr(true, "FR", "9","DOWN", "101", Queue.getQueue());
		Queue.insetfr(true, "FR", "9","DOWN", "101.5", Queue.getQueue());
		Queue.insetfr(true, "FR", "9","DOWN", "102", Queue.getQueue());
		Queue.insetfr(true, "FR", "9","DOWN", "102.5", Queue.getQueue());
		Queue.insetfr(true, "FR", "9","DOWN", "103", Queue.getQueue());
		
		Queue.insetfr(true, "FR", "8","DOWN", "100", Queue.getQueue());
		Queue.insetfr(true, "FR", "8","DOWN", "100.5", Queue.getQueue());
		Queue.insetfr(true, "FR", "8","DOWN", "101", Queue.getQueue());
		Queue.insetfr(true, "FR", "8","DOWN", "101.5", Queue.getQueue());
		Queue.insetfr(true, "FR", "8","DOWN", "102", Queue.getQueue());
		Queue.insetfr(true, "FR", "8","DOWN", "102.5", Queue.getQueue());
		Queue.insetfr(true, "FR", "8","DOWN", "103", Queue.getQueue());
		Queue.insetfr(true, "FR", "8","DOWN", "103.5", Queue.getQueue());
		Queue.insetfr(true, "FR", "8","DOWN", "104", Queue.getQueue());
		Queue.insetfr(true, "FR", "8","DOWN", "104.5", Queue.getQueue());
		Queue.insetfr(true, "FR", "8","DOWN", "105", Queue.getQueue());
		
		Queue.insetfr(true, "FR", "7","DOWN", "100", Queue.getQueue());
		Queue.insetfr(true, "FR", "7","DOWN", "100.5", Queue.getQueue());
		Queue.insetfr(true, "FR", "7","DOWN", "101", Queue.getQueue());
		Queue.insetfr(true, "FR", "7","DOWN", "101.5", Queue.getQueue());
		Queue.insetfr(true, "FR", "7","DOWN", "102", Queue.getQueue());
		Queue.insetfr(true, "FR", "7","DOWN", "102.5", Queue.getQueue());
		Queue.insetfr(true, "FR", "7","DOWN", "103", Queue.getQueue());
		Queue.insetfr(true, "FR", "7","DOWN", "103.5", Queue.getQueue());
		Queue.insetfr(true, "FR", "7","DOWN", "104", Queue.getQueue());
		Queue.insetfr(true, "FR", "7","DOWN", "104.5", Queue.getQueue());
		Queue.insetfr(true, "FR", "7","DOWN", "105", Queue.getQueue());
		
		
		NewElevator.run(Queue.getQueue());
		
		setUp();
		Queue.inseter(true,"ER", "1", "0", Queue.getQueue());
		Queue.inseter(true,"ER", "10", "0", Queue.getQueue());
		Queue.inseter(true,"ER", "2", "0", Queue.getQueue());
		Queue.inseter(true,"ER", "2", "0.5", Queue.getQueue());
		Queue.inseter(true,"ER", "2", "1", Queue.getQueue());
		Queue.inseter(true,"ER", "2", "1.5", Queue.getQueue());
		Queue.inseter(true,"ER", "2", "2", Queue.getQueue());
		Queue.inseter(true,"ER", "2", "2.5", Queue.getQueue());
		Queue.inseter(true,"ER", "2", "3", Queue.getQueue());
		Queue.inseter(true,"ER", "3", "0", Queue.getQueue());
		Queue.inseter(true,"ER", "3", "0.5", Queue.getQueue());
		Queue.inseter(true,"ER", "3", "1", Queue.getQueue());
		Queue.inseter(true,"ER", "3", "1.5", Queue.getQueue());
		Queue.inseter(true,"ER", "3", "2", Queue.getQueue());
		Queue.inseter(true,"ER", "3", "2.5", Queue.getQueue());
		Queue.inseter(true,"ER", "3", "3", Queue.getQueue());

	
		NewElevator.run(Queue.getQueue());
		
		

	}

	@Test
	public void testGetFloor() {
		NewElevator.setFloor(1);
		assertEquals(1, NewElevator.getFloor());
		
	}

	@Test
	public void testSetFloor() {
		NewElevator.setFloor(1);
		assertEquals(1, NewElevator.getFloor());
	}
	
	@Test
	public void testRepOK() {
		NewElevator.floor=-1;
		assertEquals(false, NewElevator.repOK());
		NewElevator.floor=1;
		NewElevator.headingfloor=-1;
		assertEquals(false, NewElevator.repOK());
		NewElevator.floor=1;
		NewElevator.headingfloor=1;
		NewElevator.direction="NULL";
		assertEquals(false, NewElevator.repOK());
		NewElevator.floor=1;
		NewElevator.headingfloor=1;
		NewElevator.direction="UP";
		assertEquals(true, NewElevator.repOK());
	}

}
